Beginning to explore ERCOT data. Let's first load pandas and numpy and open up one load file:

In [27]:
import numpy as np
import pandas as pd

df = pd.read_excel('/Users/mikemueller/GitHub/ercot_load_forecasting/data/raw/ercot/Native_Load_2021.xlsx')
df

,Hour Ending,COAST,EAST,FWEST,NORTH,NCENT,SOUTH,SCENT,WEST,ERCOT
0,01/01/2021 01:00,11047.018793,1517.435253,3978.220628,838.352810,13575.277728,3545.093310,7778.262533,1440.188560,43719.849616
1,01/01/2021 02:00,10954.470339,1523.683893,3975.757045,825.123437,13340.337915,3586.547882,7693.744119,1421.385715,43321.050347
2,01/01/2021 03:00,10883.657240,1519.800916,3969.812081,819.551228,13311.625189,3586.124059,7566.951524,1405.544826,43063.067063
3,01/01/2021 04:00,10926.482445,1523.472963,3983.487761,820.612439,13356.442066,3570.592369,7506.685527,1402.283632,43090.059203
4,01/01/2021 05:00,11019.796399,1565.625573,3980.940744,831.607158,13528.651487,3590.902242,7563.971854,1405.094618,43486.590073
...,...,...,...,...,...,...,...,...,...,...
8755,12/31/2021 20:00,13926.775034,1566.583851,4192.977787,916.124441,11942.416165,3910.031058,7401.098687,1133.093917,44989.100940
8756,12/31/2021 21:00,13498.908542,1549.687559,4149.062209,886.943872,11406.911057,3681.222926,7088.478765,1102.727285,43363.942215
8757,12/31/2021 22:00,13116.012129,1515.852644,4148.330779,859.408149,10978.547227,3515.077507,6800.707246,1071.686005,42005.621687
8758,12/31/2021 23:00,12754.392799,1457.080439,4161.355505,831.148872,10578.729201,3368.125857,6497.990404,1049.414195,40698.237272
8759,12/31/2021 24:00,12386.413060,1415.239264,4119.738722,807.084492,10140.379573,3234.113244,6151.440423,1016.183096,39270.591873

Now inspect the dataset:

In [28]:
df.shape

(8760, 10)

There are 10 columns and 8760 rows.

In [29]:
df.columns

Index(['Hour Ending', 'COAST', 'EAST', 'FWEST', 'NORTH', 'NCENT', 'SOUTH',
       'SCENT', 'WEST', 'ERCOT'],
      dtype='str')

The 10 columns are: 'Hour Ending', 'COAST', 'EAST', 'FWEST', 'NORTH', 'NCENT', 'SOUTH',
       'SCENT', 'WEST', 'ERCOT'. These are str type.

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Hour Ending  8760 non-null   str
 1   COAST        8760 non-null   float64
 2   EAST         8760 non-null   float64
 3   FWEST        8760 non-null   float64
 4   NORTH        8760 non-null   float64
 5   NCENT        8760 non-null   float64
 6   SOUTH        8760 non-null   float64
 7   SCENT        8760 non-null   float64
 8   WEST         8760 non-null   float64
 9   ERCOT        8760 non-null   float64
dtypes: float64(9), str(1)
memory usage: 684.5 KB

No values are null. 
Hour Ending values are str and COAST thru ERCOT are float64

In [31]:
df.head()

,Hour Ending,COAST,EAST,FWEST,NORTH,NCENT,SOUTH,SCENT,WEST,ERCOT
0,01/01/2021 01:00,11047.018793,1517.435253,3978.220628,838.352810,13575.277728,3545.093310,7778.262533,1440.188560,43719.849616
1,01/01/2021 02:00,10954.470339,1523.683893,3975.757045,825.123437,13340.337915,3586.547882,7693.744119,1421.385715,43321.050347
2,01/01/2021 03:00,10883.657240,1519.800916,3969.812081,819.551228,13311.625189,3586.124059,7566.951524,1405.544826,43063.067063
3,01/01/2021 04:00,10926.482445,1523.472963,3983.487761,820.612439,13356.442066,3570.592369,7506.685527,1402.283632,43090.059203
4,01/01/2021 05:00,11019.796399,1565.625573,3980.940744,831.607158,13528.651487,3590.902242,7563.971854,1405.094618,43486.590073

Hour Ending appears to be local time. 8 regional load columns and one total ERCOT column. LEt's confirm the columns add up.

In [ ]:
regional_total=df.iloc[:,1:9].sum(axis=1)
ercot_total=df.iloc[:,9]
df.loc[~np.isclose(regional_total,ercot_total)]
reg_erc_diff=ercot_total-regional_total
(reg_erc_diff.abs() > 1).sum()
df["reg_sum"]=regional_total
df["reg_erc_diff"]=reg_erc_diff
df["perc_diff"]=100*(reg_erc_diff/ercot_total)
df.loc[reg_erc_diff.abs() > 1, ["ERCOT","reg_sum","reg_erc_diff","perc_diff"]].describe()
list(enumerate(df.columns))

In [136]:
bad=df.iloc[reg_erc_diff>1]
bad["Hour Ending"]

3263    05/17/2021 01:00
3264    05/17/2021 02:00
3265    05/17/2021 03:00
3266    05/17/2021 04:00
3267    05/17/2021 05:00
3268    05/17/2021 06:00
3269    05/17/2021 07:00
3270    05/17/2021 08:00
3271    05/17/2021 09:00
3272    05/17/2021 10:00
3273    05/17/2021 11:00
3274    05/17/2021 12:00
3275    05/17/2021 13:00
3276    05/17/2021 14:00
3277    05/17/2021 15:00
3278    05/17/2021 16:00
3279    05/17/2021 17:00
3280    05/17/2021 18:00
3281    05/17/2021 19:00
3282    05/17/2021 20:00
3283    05/17/2021 21:00
3284    05/17/2021 22:00
3285    05/17/2021 23:00
3286    05/17/2021 24:00
3287    05/18/2021 01:00
3288    05/18/2021 02:00
3289    05/18/2021 03:00
3290    05/18/2021 04:00
3291    05/18/2021 05:00
3292    05/18/2021 06:00
3293    05/18/2021 07:00
3294    05/18/2021 08:00
3295    05/18/2021 09:00
3296    05/18/2021 10:00
3297    05/18/2021 11:00
3298    05/18/2021 12:00
3299    05/18/2021 13:00
3300    05/18/2021 14:00
3301    05/18/2021 15:00
3302    05/18/2021 16:00
3303    05/18/2021 17:00
3304    05/18/2021 18:00
3305    05/18/2021 19:00
3306    05/18/2021 20:00
3307    05/18/2021 21:00
3308    05/18/2021 22:00
3309    05/18/2021 23:00
3310    05/18/2021 24:00
Name: Hour Ending, dtype: str

In [137]:
df.describe()

,COAST,EAST,FWEST,NORTH,NCENT,SOUTH,SCENT,WEST,ERCOT,reg_sum,reg_erc_diff,perc_diff
count,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8.760000e+03,8.760000e+03
mean,12966.671036,1645.583000,4041.638084,821.408845,13420.979350,3620.112954,7108.047151,1197.338470,44828.814387,44821.778889,7.035498e+00,1.631362e-02
std,2729.996683,378.286092,481.021797,184.045078,3530.285552,855.559092,1792.602990,233.608307,9524.636890,9525.919439,9.957036e+01,2.251458e-01
min,7803.540585,995.208117,1242.334939,488.272293,7763.771846,1958.876190,4253.155232,796.642000,27800.149736,27800.149736,-3.000001e-06,-7.963983e-09
25%,10951.013278,1383.786154,3778.395313,687.189483,11058.592446,2961.084498,5840.485631,1035.986524,38145.391773,38144.708900,-7.275958e-12,-1.967784e-14
50%,12351.339093,1543.027093,4083.669498,775.778778,12404.344874,3438.455362,6608.821426,1129.282654,42339.248600,42333.485455,0.000000e+00,0.000000e+00
75%,14473.434430,1831.507104,4305.327280,927.927369,15053.430851,4207.276747,8100.303356,1314.106185,49631.333618,49609.862334,9.999931e-07,1.792532e-09
max,21157.763974,2949.198517,5127.550879,1421.300946,25851.501030,6192.252947,13188.562953,2110.021148,73650.573480,73650.573481,2.359831e+03,4.742142e+00

Not really sure what to put on markdown under head and describe. There is a lot of output.